# Generated by Django 5.1.7 on 2025-04-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_presupuestotransaccion_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.metodopago'),
        ),
    ]
