# Generated by Django 5.1.7 on 2025-04-02 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_presupuesto_categoria_presupuesto_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='presupuesto_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.presupuesto'),
        ),
        migrations.AlterUniqueTogether(
            name='presupuestotransaccion',
            unique_together={('presupuesto', 'transaccion')},
        ),
    ]
