# Generated by Django 5.1.7 on 2025-04-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaccion_presupuesto_asociado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('QR', 'QR'), ('TARJETA', 'Tarjeta')], max_length=10),
        ),
    ]
