# Generated by Django 5.1.7 on 2025-04-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_metodopago_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
    ]
